### ISSUE TITLE
Compile Time Error in my Pull Request

### ISSUE THREAD

**Issue by Andrew-K961** [FRC-Team-1710/SubTeamCalculator#7]
A compile error occurs in #3 . Here is the error: 
```
/MyClass.java:54: error: variable leadersIncludedFinalCount might not have been initialized
          return leadersIncludedFinalCount;
                 ^
/MyClass.java:84: error: variable leadersIncludedOGCount might not have been initialized
          return leadersIncludedOGCount;
                 ^
2 errors
```
It says the two variables in the methods have not been initialized but they are initialized at the top of the method right here:
```java
      public static boolean userInputLeadersInOGCount() { //Returns whether leaders were included in original count; Made by Andrew
          boolean leadersIncludedOGCount;
```
And right here:
```java
      public static boolean userInputLeadersInFinalCount() { //Returns whether leaders will be included in final count; Made by Andrew
          boolean leadersIncludedFinalCount;
```
I might have made a stupid mistake and initialized it incorrectly.

**Comment by GavenB141** [comment]
When it says the variables "might not have been initialized," it means that it's possible for the program to reach the return statement without assigning a value to the variable. Since all possible initializations are locked behind conditionals that may not be met, it returns an error. You can solve this by assigning a default value to the variables, or better yet, for the most accurate results make use of a do...while loop to ensure that a valid input is received from the user before the program moves on.
